// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kinefgssulsmbjpqsorb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpbmVmZ3NzdWxzbWJqcHFzb3JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3MTY3NTUsImV4cCI6MjA1MzI5Mjc1NX0.GDn-jt4Tmf_qFti0_h_UVMO-LzMiZUUo2MZocQG7iKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);